AllCops:
  NewCops: enable

require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
