batch_add_logdrain:
  cron: "*/10 * * * *"
  class: "BatchAddLogdrainJob"
  queue: within_one_minute

batch_formation_update:
  cron: "* * * * *"
  class: "BatchFormationUpdateJob"
  queue: within_one_minute
